/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export default class FormUtils {
  static requestSleepLiveCard() {
    console.log('[FormUtils] Request Sleep Live Card');
  }

  static requestExpressLiveCard() {
    console.log('[FormUtils] Request Express Live Card');
  }

  static requestSportsLiveCard() {
    console.log('[FormUtils] Request Sports Live Card');
  }

  static requestMusicLiveCard() {
    console.log('[FormUtils] Request Music Live Card');
  }

  static requestWeatherLiveCard() {
    console.log('[FormUtils] Request Weather Live Card');
  }

  static requestSmartHomeLiveCard() {
    console.log('[FormUtils] Request SmartHome Live Card');
  }
}
