/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import formBindingData from '@ohos.app.form.formBindingData';
import formManager from '@ohos.app.form.formManager';
import Want from '@ohos.app.ability.Want';

export default class FormUtils {
  static requestSleepLiveCard(): void {
    console.log('Request Sleep Live Card');
  }

  static requestExpressLiveCard(): void {
    console.log('Request Express Live Card');
  }

  static requestSportsLiveCard(): void {
    console.log('Request Sports Live Card');
  }

  static requestMusicLiveCard(): void {
    console.log('Request Music Live Card');
  }

  static requestWeatherLiveCard(): void {
    console.log('Request Weather Live Card');
  }

  static requestSmartHomeLiveCard(): void {
    console.log('Request Smart Home Live Card');
  }
}
